version: "3.8"
services:
  app:
    image: rica
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules